"""
train_and_export.py
SRS 8.6.3 / 9.5 — trains the two Edge AI models offline and exports them
as plain C code (model.h) for direct #include in the ESP32 firmware.

  Arrival model   : Logistic Regression  -> predictArrival()
  Duration model  : Decision Tree Regr.  -> predictDuration()

Feature order (must match firmware/include/model.h and edge_ai.cpp):
  [hourOfDay, dayOfWeek, bayOccupied, recentAvgCurrent, sessionElapsedMin]

Usage:
    python generate_dataset.py --rows 8000
    python train_and_export.py --csv synthetic_ev_data.csv --out ../firmware/include/model.h
"""
import argparse
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score

FEATURES = ["hourOfDay", "dayOfWeek", "bayOccupied", "recentAvgCurrent", "sessionElapsedMin"]

HEADER_GUARD_TOP = """#ifndef MODEL_H
#define MODEL_H

// =======================================================================
// AUTO-GENERATED by ai_training/train_and_export.py — DO NOT HAND-EDIT.
// SRS 8.6.3 / 9.5 — trained Edge AI models exported to C.
//
// Input feature order (SRS 8.6.2), same order used by both functions:
//   features[0] = hourOfDay          (0-23)
//   features[1] = dayOfWeek          (0-6, 0=Sunday)
//   features[2] = bayOccupied        (0 or 1)
//   features[3] = recentAvgCurrent   (A)
//   features[4] = sessionElapsedMin  (minutes, 0 if FREE)
// =======================================================================

"""
HEADER_GUARD_BOTTOM = "\n#endif\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", type=str, default="synthetic_ev_data.csv")
    ap.add_argument("--out", type=str, default="../firmware/include/model.h")
    args = ap.parse_args()

    df = pd.read_csv(args.csv)

    # ---- Arrival probability model (all rows) ----
    X_arrival = df[FEATURES]
    y_arrival = df["arrivedWithinWindow"]
    Xtr, Xte, ytr, yte = train_test_split(X_arrival, y_arrival, test_size=0.2, random_state=42)
    arrival_model = LogisticRegression(max_iter=1000).fit(Xtr, ytr)
    acc = accuracy_score(yte, arrival_model.predict(Xte))
    print(f"Arrival model accuracy: {acc:.3f}")

    # ---- Session duration model (only occupied bays) ----
    occ = df[df.bayOccupied == 1]
    X_duration = occ[FEATURES]
    y_duration = occ["actualDurationMin"]
    Xtr2, Xte2, ytr2, yte2 = train_test_split(X_duration, y_duration, test_size=0.2, random_state=42)
    duration_model = DecisionTreeRegressor(max_depth=5, random_state=42).fit(Xtr2, ytr2)
    r2 = r2_score(yte2, duration_model.predict(Xte2))
    print(f"Duration model R^2: {r2:.3f}")

    # ---- Export to C ----
    # SRS 8.6.3 names m2cgen for linear/logistic models and micromlgen for
    # trees. In practice m2cgen also exports DecisionTreeRegressor cleanly
    # to portable C, so both models are exported through m2cgen here for a
    # single, reliably-working dependency; micromlgen is kept as a documented
    # fallback for the duration model below if you prefer the SRS's exact split.
    try:
        import m2cgen as m2c
    except ImportError:
        raise SystemExit("Install dependencies first: pip install m2cgen micromlgen --break-system-packages")

    arrival_c_raw = m2c.export_to_c(arrival_model)
    # m2cgen's generated function is `double score(double input[])`. We wrap it
    # in the inline float function our firmware expects, matching model.h's stub API,
    # and clamp the logistic output to [0,1] (m2cgen's LogisticRegression export
    # already applies the sigmoid, so score() *is* the probability).
    arrival_c = arrival_c_raw.replace("double score(double * input)", "static double _arrival_score(double * input)")

    try:
        duration_c_raw = m2c.export_to_c(duration_model)
    except Exception:
        # Fallback exactly as SRS 8.6.3 describes: micromlgen for the tree.
        from micromlgen import port
        duration_c_raw = port(duration_model)
    duration_c = duration_c_raw.replace("double score(double * input)", "static double _duration_score(double * input)")
    duration_c = duration_c.replace("double predict(double * input)", "static double _duration_score(double * input)")

    wrapper = """
inline float predictArrival(float features[5]) {
  double input[5] = { features[0], features[1], features[2], features[3], features[4] };
  double p = _arrival_score(input);
  if (p < 0.0) p = 0.0;
  if (p > 1.0) p = 1.0;
  return (float)p;
}

inline float predictDuration(float features[5]) {
  double input[5] = { features[0], features[1], features[2], features[3], features[4] };
  double d = _duration_score(input);
  if (d < 0.0) d = 0.0;
  return (float)d;
}
"""

    with open(args.out, "w") as f:
        f.write(HEADER_GUARD_TOP)
        f.write("// ---- Arrival probability model (Logistic Regression) ----\n")
        f.write(arrival_c)
        f.write("\n\n// ---- Session duration model (Decision Tree Regressor) ----\n")
        f.write(duration_c)
        f.write("\n\n// ---- Firmware-facing wrapper functions ----\n")
        f.write(wrapper)
        f.write(HEADER_GUARD_BOTTOM)

    print(f"Wrote trained model.h to {args.out}")
    print("Copy/verify it replaces firmware/include/model.h, then rebuild the firmware.")


if __name__ == "__main__":
    main()
